vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile_photos:
            uri_prefix: /uploads/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        cv_files:
            uri_prefix: /uploads/cv
            upload_destination: '%kernel.project_dir%/public/uploads/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        content_files:
            uri_prefix: /uploads/content
            upload_destination: '%kernel.project_dir%/public/uploads/content'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        course_documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
